---

- hosts: revproxy
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - apache

- hosts: appserver
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - selinux
    - tomcat
